version: "3"

services:

  web:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 5000:5000
    environment:
      - CONFIG
      - REDIS_URL
      - SQLALCHEMY_DATABASE_URI
      - S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - .:/app

  worker:
    build: .
    container_name: worker
    command: python uwsgi.py taskworker
    depends_on:
      - redis
    volumes:
      - .:/app


  db:
    image: postgres:latest
    container_name: boa_db
    restart: always
    environment:
      - POSTGRES_DB=boa
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
