version: "3.7"

services:
  boa:
    build: .
    image: boa
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    environment:
      - FLASK_APP
      - AWS_S3_BUCKET
      - AWS_S3_KEY
      - AWS_S3_SECRET
    container_name: boa
    command: gunicorn app:app
    volumes:
      - .:/usr/src/boa

  # TODO: setup database container
