version: "3.7"

services:
  app:
    build: .
    image: boa
    depends_on:
      - db
    ports:
      - 5000:80
    environment:
      - SQLALCHEMY_DATABASE_URI
      - S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    networks:
      - default
    volumes:
      - .:/usr/src/boa

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - default
    ports:
      - 5405:5432
    volumes:
      - ./db:/var/lib/postgresql/db
