version: "3.7"

services:
  boa:
    build: .
    image: boa
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      - FLASK_APP
      - SQLALCHEMY_DATABASE_URI
      - AWS_S3_BUCKET
      - AWS_S3_KEY
      - AWS_S3_SECRET
    networks:
      - default
    volumes:
      - .:/usr/src/boa

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PWD
      - POSTGRES_DB
    networks:
      - default
    ports:
      - 5405:5432
    volumes:
      - ./db:/var/lib/postgresql/db
