version: "3"

services:

  web:
    build: boa-web/
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 5000:5000
    environment:
      - CONFIG

      # default, can be overriden
      - REDIS_URL=redis://redis:6379
      - SQLALCHEMY_DATABASE_URI=postgresql://manager:password@db:5432/boa

      # user-supplied envvars for S3; if not set, not uploaded
      - S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: boa_db
    restart: always
    environment:
      - POSTGRES_DB=boa
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
