version: "3"

services:
  app:
    build: .
    image: boa
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - SQLALCHEMY_DATABASE_URI
      - S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - .:/usr/src/boa

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=boa
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
