version: "3.7"

services:

  boa:
    build: .
    image: boa
    container_name: boa
    ports:
      - 8000:5000
    command: gunicorn app:app
    volumes:
      - .:/usr/src/boa
    depends_on:
      - redis

  redis:
    image: redis:5.0.7-alpine

  dashboard:
    image: eoranged/rq-dashboard
    ports:
      - 9181:9181
    depends_on:
      - redis
