version: "3"

services:

  boa:
    build: .
    container_name: boa
    restart: always
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      - SQLALCHEMY_DATABASE_URI
      - S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DEBUG_MODE=false
    volumes:
      - /tmp:/mnt/boa

  db:
    image: postgres:latest
    container_name: boa_db
    restart: always
    environment:
      - POSTGRES_DB=boa
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    container_name: redis

  dashboard:
    build: ./dashboard
    image: dashboard
    container_name: dashboard
    depends_on:
      - redis
    ports:
      - 9181:9181
    command: rq-dashboard -H redis
